'use client'

import { useState } from 'react'
import { CheckCircle2, FileUp, UploadCloud } from 'lucide-react'

const steps = ['Upload', 'Map columns', 'Select enrichment', 'Preview cost', 'Run']

export default function EnrichmentPage() {
  const [fileName, setFileName] = useState('')
  return <main className="min-h-screen bg-background text-foreground"><header className="border-b px-4 py-5 sm:px-8"><div className="mx-auto max-w-6xl"><p className="text-xs text-muted-foreground">Operations / Enrichment</p><h1 className="mt-2 text-2xl font-semibold tracking-tight">Enrich your records</h1><p className="mt-1 text-sm text-muted-foreground">Bring your own data and add traceable business intelligence without losing partial results.</p></div></header><div className="mx-auto max-w-6xl px-4 py-6 sm:px-8"><div className="mb-8 grid grid-cols-5 gap-1 sm:gap-3">{steps.map((step, index) => <div key={step} className="flex flex-col gap-2"><div className={`h-1 rounded-full ${index === 0 ? 'bg-foreground' : 'bg-muted'}`} /><span className={`text-[10px] sm:text-xs ${index === 0 ? 'font-medium text-foreground' : 'text-muted-foreground'}`}>{step}</span></div>)}</div><section className="max-w-2xl rounded-lg border bg-card"><div className="border-b px-5 py-4"><h2 className="text-sm font-semibold">Upload a CSV</h2><p className="mt-1 text-xs text-muted-foreground">Use a company domain, company name, or professional profile URL as an identifier.</p></div><label className="m-5 flex min-h-56 cursor-pointer flex-col items-center justify-center rounded-md border border-dashed bg-muted/20 px-6 text-center transition-colors hover:bg-muted/40"><input type="file" accept=".csv,text/csv" className="sr-only" onChange={(event) => setFileName(event.target.files?.[0]?.name ?? '')} /><div className="mb-3 flex size-11 items-center justify-center rounded-full border bg-background">{fileName ? <CheckCircle2 className="size-5" /> : <UploadCloud className="size-5 text-muted-foreground" />}</div><p className="text-sm font-medium">{fileName || 'Choose a CSV file'}</p><p className="mt-1 text-xs text-muted-foreground">Maximum 50 MB. We will validate columns before processing.</p></label><div className="flex flex-col gap-3 border-t px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><p className="flex items-center gap-2 text-xs text-muted-foreground"><FileUp className="size-3.5" /> No data is processed until you confirm.</p><button disabled={!fileName} className="min-h-10 rounded-md bg-foreground px-4 text-sm font-medium text-background disabled:cursor-not-allowed disabled:opacity-40">Continue</button></div></section></div></main>
}
