'use client'

import { useState } from 'react'
import { Building2, ChevronDown, Filter, Search, SlidersHorizontal } from 'lucide-react'

export default function CompaniesPage() {
  const [query, setQuery] = useState('')
  return <main className="min-h-screen bg-background text-foreground"><header className="border-b px-4 py-5 sm:px-8"><div className="mx-auto flex max-w-6xl items-center justify-between"><div><p className="text-xs text-muted-foreground">Intelligence / Companies</p><h1 className="mt-2 text-2xl font-semibold tracking-tight">Company search</h1><p className="mt-1 text-sm text-muted-foreground">Find businesses by firmographics, technology, and intent signals.</p></div><button className="hidden min-h-10 items-center gap-2 rounded-md border px-3 text-sm font-medium sm:flex"><SlidersHorizontal className="size-4" /> Saved searches</button></div></header><div className="mx-auto max-w-6xl px-4 py-6 sm:px-8"><div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-3 size-4 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search by company, domain, keyword, or technology" className="min-h-11 w-full rounded-md border bg-card pl-10 pr-4 text-base outline-none ring-offset-background placeholder:text-muted-foreground focus:ring-2 focus:ring-ring" /></label><button className="inline-flex min-h-11 items-center justify-center gap-2 rounded-md border px-4 text-sm font-medium"><Filter className="size-4" /> Filters <span className="rounded-full bg-muted px-1.5 text-xs">0</span></button></div><div className="mt-5 flex flex-wrap gap-2"><button className="inline-flex min-h-9 items-center gap-2 rounded-md border px-3 text-xs text-muted-foreground">Industry <ChevronDown className="size-3.5" /></button><button className="inline-flex min-h-9 items-center gap-2 rounded-md border px-3 text-xs text-muted-foreground">Location <ChevronDown className="size-3.5" /></button><button className="inline-flex min-h-9 items-center gap-2 rounded-md border px-3 text-xs text-muted-foreground">Employee count <ChevronDown className="size-3.5" /></button></div><section className="mt-6 overflow-hidden rounded-lg border bg-card"><div className="flex items-center justify-between border-b px-4 py-4 sm:px-5"><div><h2 className="text-sm font-semibold">Companies</h2><p className="mt-1 text-xs text-muted-foreground">{query ? `Results for “${query}”` : 'Run a search to discover companies'}</p></div><span className="text-xs text-muted-foreground">0 results</span></div><div className="flex min-h-[330px] flex-col items-center justify-center px-6 py-12 text-center"><div className="mb-4 flex size-11 items-center justify-center rounded-full border bg-muted/40"><Building2 className="size-5 text-muted-foreground" /></div><h3 className="text-sm font-medium">No companies found yet</h3><p className="mt-1 max-w-sm text-xs leading-5 text-muted-foreground">Connect a licensed data provider or import your own records to start building a traceable company dataset.</p></div></section></div></main>
}
